[package]
name = "rustyjeff"
version = "0.1.2"
authors = ["Kashim Aziz <kaziz@bink.com>", "Chris Latham <cl@bink.com>"]
edition = "2018"
readme = "README.md"

[lib]
name = "rustyjeff"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]

[dependencies]
openssl = "0.10.30"
base64 = "0.12.3"
rayon = "1.3.1"
